name: build
on:
  push:
    branches:
      - main
permissions: read-all|write-all
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip
      - run: pip install mkdocs mkdocs-pymdownx-material-extras
      - run: mkdocs gh-deploy --force --clean --verbose
